programs:
  ping1:
    cmd: "ping google.com"
    num_processes: 2
    autostart: true
    restart_policy: "Always"
    expected_error_codes:
      - 0
      - 2
    minimum_runtime: 5
    max_relauch_retry: 4
    stop_signal: Sigterm
    time_after_proper_stop: 10
    redirect:
      stdout: "ping1_stdout.txt"
      stderr: "ping1_stderr.txt"
    env_to_set:
      chien: "chat"
    umask: 022
