programs:
  ping1:
    cmd: "ping 42.com"
    num_processes: 2
    autostart: true
    restart_policy: "Always"
    expected_error_codes:
      - 0
      - 2
    minimum_runtime: 5
    max_relauch_retry: 4
    stop_signal: SIGTERM
    time_after_proper_stop: 10
    redirect:
      stdout: "ping1_stdout.txt"
      stderr: "ping1_stderr.txt"
    env_to_set:
      chien: "chat"
    umask: 022
  env2:
    cmd: "./testprogs/return_code/return_code"
    num_processes: 1
    autostart: false
    restart_policy: "UnexpectedExits"
    expected_error_codes:
      - 0
      - 1
    minimum_runtime: 5
    max_relauch_retry: 4
    stop_signal: SIGTERM
    time_after_proper_stop: 10
    redirect:
      stdout: "env2_stdout.txt"
      stderr: "env2_stderr.txt"
    umask: 022
